#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate docs/index.md and docs/reference.md from the repo source Markdown files for MkDocs.

Source Markdown keeps relative links (good for GitHub and local editing).
Generated pages rewrite most repo-relative links to GitHub blob URLs; cross-links
between top-level docs use MkDocs sibling pages (`index.md` / `reference.md` /
`integration.md` / `examples.md`) so the site stays in-docs.

Resolve blob base (first match):
  1. DOCS_REPO_BLOB_BASE — full prefix including branch, e.g. https://github.com/owner/repo/blob/develop
  2. GITHUB_REPOSITORY + branch (see repo_branch())
  3. git remote origin + branch

Branch for /blob/<branch>/... (ignored if DOCS_REPO_BLOB_BASE is set), first match:
  - DOCS_REPO_BRANCH — e.g. develop or main
  - GITHUB_REF_NAME — set in GitHub Actions to the triggering branch
  - git rev-parse --abbrev-ref HEAD — current local branch
  - main — fallback if not in a git repo or detached HEAD

Usage: python scripts/generate_docs_pages.py
  DOCS_REPO_BRANCH=develop python scripts/generate_docs_pages.py
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def repo_branch() -> str:
    explicit = os.environ.get("DOCS_REPO_BRANCH", "").strip()
    if explicit:
        return explicit
    ref = os.environ.get("GITHUB_REF_NAME", "").strip()
    if ref:
        return ref
    try:
        head = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "--abbrev-ref", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        head = ""
    if head and head != "HEAD":
        return head
    return "main"


def blob_base() -> str:
    explicit = os.environ.get("DOCS_REPO_BLOB_BASE", "").strip().rstrip("/")
    if explicit:
        return explicit
    branch = repo_branch()
    gh = os.environ.get("GITHUB_REPOSITORY", "").strip()
    if gh:
        return f"https://github.com/{gh}/blob/{branch}"
    try:
        url = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "remote", "get-url", "origin"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        url = ""
    m = re.search(r"github\.com[:/]([^/]+)/([^/.]+)", url)
    if m:
        return f"https://github.com/{m.group(1)}/{m.group(2)}/blob/{branch}"
    print(
        "Could not resolve GitHub blob base. Set DOCS_REPO_BLOB_BASE "
        "or GITHUB_REPOSITORY, or add a github.com remote named origin.",
        file=sys.stderr,
    )
    sys.exit(1)


def main() -> None:
    base = blob_base()

    # Generate index.md from README.md
    root = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    root_out = (
        root.replace("](./core/REFERENCE.md)", "](reference.md)")
        .replace("](core/REFERENCE.md)", "](reference.md)")
        .replace("](core/REFERENCE.md#", "](reference.md#")
        .replace("](INTEGRATION.md#", "](integration.md#")
        .replace("](INTEGRATION.md)", "](integration.md)")
        .replace("](EXAMPLES.md#", "](examples.md#")
        .replace("](EXAMPLES.md)", "](examples.md)")
        .replace("](LICENSE)", f"]({base}/LICENSE)")
        .replace("](core/", f"]({base}/core/")
    )

    index = REPO_ROOT / "docs" / "index.md"
    index.write_text(
        "<!-- Generated by scripts/generate_docs_pages.py — edit README.md, not this file. -->\n\n"
        + root_out,
        encoding="utf-8",
    )

    # Generate reference.md from core/REFERENCE.md
    _core_reference = REPO_ROOT / "core" / "REFERENCE.md"
    _core_banner = (
        "<!-- Generated by scripts/generate_docs_pages.py — "
        "edit core/REFERENCE.md, not this file. -->\n\n"
    )
    core = _core_reference.read_text(encoding="utf-8")
    if core.startswith(_core_banner):
        core = core[len(_core_banner) :]
    core_out = (
        core.replace("](src/", f"]({base}/core/src/")
        .replace("](../README.md#", "](index.md#")
        .replace("](../README.md)", "](index.md)")
        .replace("](REFERENCE.md#", "](reference.md#")
        .replace("](REFERENCE.md)", "](reference.md)")
        .replace("](../EXAMPLES.md#", "](examples.md#")
        .replace("](../EXAMPLES.md)", "](examples.md)")
        .replace("](../INTEGRATION.md#", "](integration.md#")
        .replace("](../INTEGRATION.md)", "](integration.md)")
    )

    reference_doc = REPO_ROOT / "docs" / "reference.md"
    reference_doc.write_text(
        "<!-- Generated by scripts/generate_docs_pages.py — edit core/REFERENCE.md, not this file. -->\n\n"
        + core_out,
        encoding="utf-8",
    )

    # Generate integration.md from INTEGRATION.md
    integration = (REPO_ROOT / "INTEGRATION.md").read_text(encoding="utf-8")
    integration_out = (
        integration.replace("](EXAMPLES.md#", "](examples.md#")
        .replace("](EXAMPLES.md)", "](examples.md)")
        .replace("](core/REFERENCE.md#", "](reference.md#")
        .replace("](core/REFERENCE.md)", "](reference.md)")
        .replace("](README.md#", "](index.md#")
        .replace("](README.md)", "](index.md)")
    )

    integration_doc = REPO_ROOT / "docs" / "integration.md"
    integration_doc.write_text(
        "<!-- Generated by scripts/generate_docs_pages.py — edit INTEGRATION.md, not this file. -->\n\n"
        + integration_out,
        encoding="utf-8",
    )

    # Generate examples.md from EXAMPLES.md
    examples = (REPO_ROOT / "EXAMPLES.md").read_text(encoding="utf-8")
    examples_out = (
        examples.replace("](core/REFERENCE.md#", "](reference.md#")
        .replace("](core/REFERENCE.md)", "](reference.md)")
        .replace("](INTEGRATION.md#", "](integration.md#")
        .replace("](INTEGRATION.md)", "](integration.md)")
        .replace("](README.md#", "](index.md#")
        .replace("](README.md)", "](index.md)")
    )

    examples_doc = REPO_ROOT / "docs" / "examples.md"
    examples_doc.write_text(
        "<!-- Generated by scripts/generate_docs_pages.py — edit EXAMPLES.md, not this file. -->\n\n"
        + examples_out,
        encoding="utf-8",
    )

    print(f"Wrote {index.relative_to(REPO_ROOT)}, {reference_doc.relative_to(REPO_ROOT)}, {integration_doc.relative_to(REPO_ROOT)}, and {examples_doc.relative_to(REPO_ROOT)}")
    print(f"Blob base: {base}")
    if not os.environ.get("DOCS_REPO_BLOB_BASE", "").strip():
        print(f"Branch: {repo_branch()}")


if __name__ == "__main__":
    main()
